- name: "[HAPROXY] - role to install haproxy"
  hosts: haproxy
  become: yes
  roles:
    - haproxy
    - consul
  tags:
    - haproxy

- name: "[CONSUL] - role to install consul"
  hosts: consul
  become: yes
  roles:
    - consul
  tags:
    - consul

- name: "[MYAPP] - install appli"
  hosts: myapp
  become: yes
  roles:
    - app
    - consul
    - consul_services
  tags:
    - myapp
