- name: "apt update"
  apt:
    update-cache: yes
    cache_valid_time: 3600

- name: "install utils"
  apt:
    name:
      - python3-flask

- name: "create directory myapp"
  file:
    path: /myapp
    state: directory
    mode: 0755

- name: "copy myapp file"
  copy:
    src: myapp.py
    dest: /myapp
    mode : 0755
  notify: restart_myapp

- name: "create service myapp"
  template:
    src: myapp.service.j2
    dest: /etc/systemd/system/myapp.service
  notify: restart_myapp

- name: "start service myapp"
  service:
    name: myapp
    state: started

  
