- name: test master
  file:
    path: /tmp/master
    state: touch
    mode: 0755

- name: create service consul for master    
  template:
    src: master.consul.service.j2           
    dest: /etc/systemd/system/consul.service

- name: create config consul for master     
  template:
    src: master.conf.json.j2
    dest: /etc/consul.d/conf.json 

